#!/usr/bin/env bun

import { app, $ } from "@gutenye/script.js";

const HELP = `
marimo edit a.py

jupyter start
jupyter deploy
`;

app.help(HELP);

app
  .cmd("marimo", "Run marimo")
  .add("[...args]", "Args")
  .add(async (args) => {
    await $`poetry run marimo ${args}`;
  });

app.cmd("jupyter start", "Start jupyter lab").add(async () => {
  await $`poetry run jupyter lab`;
});

app.cmd("jupyter deploy", "Deploy jupyter report").add(async () => {
  await $`poetry run quarto render Expense/Expense.ipynb --execute --output-dir ./public`;
  await $`netlify deploy --prod`;
});
